CUDA_VISIBLE_DEVICES=0 python main.py \
    --device cuda \
    --dataset NUSWIDE \
    --notes "nus_wide/16bits" \
    --trainable_layer_num 0 \
    --M 2 \
    --feat_dim 32 \
    --T 0.2 \
    --hp_beta 5e-3 \
    --softmax_temp 5.0 \
    --clip_r 0.8 \
    --init_neg_curvs 1.0 \
    --full_hyperpq \
    --disable_writer \
    --epoch_num 50 \
    --clus_mode "hier_clus" \
    --num_clus_list "200,100,75" \
    --warmup_epoch 3 \
    --eval_interval 1 \
    --topK 5000 
